### ISSUE TITLE
Request: Add reconnectionPolicy, reconnectionInteval, and reconnectionBound 

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.objectstorage#190]
The ability to configure the scan/source/sink operators to retry when connections are not available would be great.  We have had times when connection to the S3 repository is temporarily unavailable, and PE's fail.  It would be nice if this could be handled more gracefully.

Thanks,
Brian

**Comment by markheger** [comment]
It is not possible to introduce such parameters since the operators are implemented on top of org.apache.hadoop.fs.FileSystem and the S3 clients are not directly used.

Nevertheless several changes improved the error handling.
a) updated client versions (_use toolkit release 2.0.0 and later_)
b) Resolved issues #191, #193, #194 improved the connection failure handling _-> use toolkit release 2.0.2 or later_
c) New parameter to configure maximum attempts: the number of times the client retries on errors (issue #196). _-> use 2.1.0 or later_

Errors/exceptions causing PE restart occur for the ObjectStorageSink:
* when using s3a protocol at operator startup when connection is not available
* when using consistent region, then the errors should trigger a reset of the region

Otherwise the metrics `nWriteFailures` and `nCloseFailures` are incremented and Sink operator is able to continue without PE restart when connection is available again.
