### ISSUE TITLE
Operators should support application configurations.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#71]
Rather than forcing use of parameters for endpoints and authentication information the operators should support application configurations, to separate configuration from the application.

**Comment by markheger** [comment]
Application configuration parameter should support a JSON string containing the credentials. In best case the IBM COS credentials could be set with copy&paste from the IBM COS service page to application configuration parameter value.
Operator needs to be able to support two JSON configurations:

**1**) `IAM`

    {
      "apikey": "xxxxxxxx",
      "endpoints": "https://cos-service.bluemix.net/endpoints",
      "iam_apikey_description": "Auto generated apikey during resource-key operation for Instance - crn:v1:bluemix:public:cloud-object-storage:global:a/xxxxxx::",
      "iam_apikey_name": "auto-generated-apikey-xxxx",
      "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
      "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/xxxxxxxx",
      "resource_instance_id": "crn:v1:bluemix:public:cloud-object-storage:global:a/xxxxxx"
    }

Where "iam_apikey_description", "iam_apikey_name", "iam_role_crn" and iam_serviceid_crn are optional and ignored since not needed.

**2**) `Basic` authentication:

    {
      "endpoint": "s3-api.us-geo.objectstorage.softlayer.net",
      "access_key": "xxxxx",
      "secret_access_key": "xxxxxxx"
    }

**Comment by ddebrunner** [comment]
The JSON would have to be the value for a property in the app config, e.g. `credentials` or similar.

Then other properties in the app config could potentially map to operator parameters.
